### ISSUE TITLE
secrets.json is required?

### ISSUE THREAD

**Issue by mathiasmadsen** [wildbit/mailmason#23] opened 2016-11-10 10:19 UTC
Hi, I have just initiated the development of a project using mailmason. It looks very promising :)

When following your guide, it is stated that secrets.json is not required. However, I was met with the following error when using 'npm start':
`..ERROR`
`>> Unable to process task.`
`Warning: Required config property "watch" missing.`

When secrets.json was created everything works, so I expect there is some kind of ignore-function that is not activated?

**Comment by garrettdimon** [comment] 2016-11-10 14:53
Thanks, Mathias. My guess is that this is just an oversight on our part. The secrets are only necessary if you're using sending or FTP'ing, but the file itself is probably a dependency in there.

@derekrushforth Is there an easy way to have Grunt look the other way when the secrets.json file is missing? Or should we update the documentation to explain that while you don't have to populate secrets, the file itself should be present?

**Comment by derekrushforth** [comment] 2016-11-15 17:31
Thanks for letting us know about this, @mathiasmadsen. I just merged a fix so that secrets.json is optional. Let me know if this works for you.

**Comment by Spone** [comment] 2017-01-23 11:01
Same problem here, with the latest version from Github. When I rune `npm start`, I get an infinite loop of this error:

```
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing.
```

**Comment by derekrushforth** [comment] 2017-01-23 20:46
Hey @Spone, have you added a JSON config from this [step](https://github.com/wildbit/mailmason/wiki/Getting-Started#configjson)? Seems like that may be causing your issue since the config is required to build your emails.

I need to update the wiki so it's clearer that config.json is required and secrets.json is optional.

**Comment by Spone** [comment] 2017-01-23 21:17
Thanks for the reply. I have both `config.json` and `secrets.json` in the root folder.

**Comment by derekrushforth** [comment] 2017-01-23 21:18
@Spone Do you see any comments at the top of those JSON files?

**Comment by Spone** [comment] 2017-01-23 22:02
Good catch! I forgot to remove the comments 😓 

Maybe a more explicit error message when the JSON files are invalid?

**Comment by derekrushforth** [comment] 2017-01-23 22:06
@Spone Glad that fixed it! Unfortunately, we have no control over this error message since it's coming from one of the grunt plugins. I know this can be a pain because I've come across this too ☹️ 

We may consider removing the comments from the example configs entirely if this becomes a bigger issue.

**Closed by derekrushforth** 2017-01-23 22:06 UTC

**Comment by GriffinSauce** [comment] 2017-12-15 12:53
Had the same problem but it was caused by a missing `}` in the JSON. I added this to our gruntfile:
```
module.exports = function(grunt) {

  // Check validity of config.json and secrets.json
  const fs = require('fs');
  const config = fs.readFileSync(`${__dirname}/config.json`, 'utf8');
  const secrets = fs.readFileSync(`${__dirname}/secrets.json`, 'utf8');
  try {
    JSON.parse(config);
  } catch (e) {
    throw Error(`config.json invalid, ${e.message}`);
  }
  try {
    JSON.parse(secrets);
  } catch (e) {
    throw Error(`secrets.json invalid, ${e.message}`);
  }
```
`readFileSync` will throw a pretty obvious error when a file is missing.
